### ISSUE TITLE
compilation error :  unit tests fail to compile with `aarch64-none-linux-gnu-g++ v11.3.rel1`

### ISSUE THREAD

**Issue by maxmarsc** [ARM-software/armnn#728]
When compiling armnn `v23.05` with unit testing enabled, some tests fails to compile due to multiple definition error :
```
[build] /usr/local/aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/../../../../aarch64-none-linux-gnu/bin/ld: libarmnn.a(Runtime.cpp.o): in function `armnn::GetMemoryOptimizerStrategy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
[build] Runtime.cpp:(.text+0x2ac0): multiple definition of `armnn::GetMemoryOptimizerStrategy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'; src/backends/backendsCommon/memoryOptimizerStrategyLibrary/test/CMakeFiles/armnnMemoryOptimizationStrategiesUnitTests.dir/MemoryOptimizerStrategyLibraryTests.cpp.o:MemoryOptimizerStrategyLibraryTests.cpp:(.text+0xa50): first defined here
[build] /usr/local/aarch64-none-linux-gnu/bin/../lib/gcc/aarch64-none-linux-gnu/11.3.1/../../../../aarch64-none-linux-gnu/bin/ld: libarmnn.a(Runtime.cpp.o): in function `armnn::GetMemoryOptimizerStrategyNames[abi:cxx11]()':
[build] Runtime.cpp:(.text+0x2c30): multiple definition of `armnn::GetMemoryOptimizerStrategyNames[abi:cxx11]()'; src/backends/backendsCommon/memoryOptimizerStrategyLibrary/test/CMakeFiles/armnnMemoryOptimizationStrategiesUnitTests.dir/MemoryOptimizerStrategyLibraryTests.cpp.o:MemoryOptimizerStrategyLibraryTests.cpp:(.text+0xbc0): first defined here
[build] collect2: error: ld returned 1 exit status
```

What I deduced from this error message :
 - [GetMemoryOptimizerStrategy](https://github.com/ARM-software/armnn/blob/49f609d9e633f52fcdc98e6e06178e618597e87d/src/backends/backendsCommon/memoryOptimizerStrategyLibrary/MemoryOptimizerStrategyLibrary.hpp#L36) is defined both in `MemoryOptimizerStrategyLibraryTests.cpp` translation unit and `Runtime.cpp` translation unit
 - same for [GetMemoryOptimizerStrategyNames](https://github.com/ARM-software/armnn/blob/49f609d9e633f52fcdc98e6e06178e618597e87d/src/backends/backendsCommon/memoryOptimizerStrategyLibrary/MemoryOptimizerStrategyLibrary.hpp#L47)
 
 A possible fix for this would be to mark both functions as `inline` to allow multiple definitions, like this :
 ```cpp
 inline std::unique_ptr<IMemoryOptimizerStrategy> GetMemoryOptimizerStrategy(const std::string& strategyName)
{
     const auto& strategyFactoryMap = GetStrategyFactories();
     auto strategyFactory = strategyFactoryMap.find(strategyName);
     if (strategyFactory != GetStrategyFactories().end())
     {
         return  strategyFactory->second->CreateMemoryOptimizerStrategy();
     }
    return nullptr;
}

inline const std::vector<std::string> GetMemoryOptimizerStrategyNames()
{
    const auto& strategyFactoryMap = GetStrategyFactories();
    std::vector<std::string> strategyNames;
    for (const auto& strategyFactory : strategyFactoryMap)
    {
        strategyNames.emplace_back(strategyFactory.first);
    }
    return strategyNames;
}
 ```
 
 *This is only a suggestion, you could want to deal with this in another way, I'll wait for answer and discussion before getting into gerrit for a pull request since I don't know the Gerrit workflow yet*
 
 My setup is :
  - `CMake 3.26.3`
  - `GNU cross compilation toolchain aarch64-none-linux-gnu v11.3.rel1`
  - `Ubuntu 20.04`

The CMake flags I used :
```
    -DBUILD_CLASSIC_DELEGATE=OFF
    -DARMCOMPUTENEON=ON
    -DTOSA_REFERENCE_MODEL_OUTPUT=OFF
    -DBUILD_SHARED_LIBS=OFF
    -DARMCOMPUTE_ROOT=...
    -DARMCOMPUTE_LIBRARIES:STRING=...
```

**Comment by Ducky-twow** [comment]
Hey maxmarsc,

Sorry for the delay on responding to this. Normally our preference in these situations is to split the functions off into their own .cpp file. However since this is only used in two places, and one of them is tests, just declaring them as inline is probably a simpler and easier solution. I'll add a patch for it later, but I wanted to ask some questions about how you're building this as we are not seeing the same errors on our end. 

Are you including the Ref or OpenCL backends or is it just Neon?
I'm assuming this is cross compilation on an x86 system?
Are you using the build tool or compiling everything manually yourself? (https://github.com/ARM-software/armnn/blob/branches/armnn_23_05/build-tool/README.md)

**Comment by davmon01** [comment]
Hey maxmarsc,

Sorry for the delay on responding to this. Normally our preference in these situations is to split the functions off into their own .cpp file. However since this is only used in two places, and one of them is tests, just declaring them as inline is probably a simpler and easier solution. I'll add a patch for it later, but I wanted to ask some questions about how you're building this as we are not seeing the same errors on our end. 

Are you including the Ref or OpenCL backends or is it just Neon?
I'm assuming this is cross compilation on an x86 system?
Are you using the build tool or compiling everything manually yourself? (https://github.com/ARM-software/armnn/blob/branches/armnn_23_05/build-tool/README.md)

**Comment by davmon01** [comment]
https://review.mlplatform.org/c/ml/armnn/+/9867

**Comment by maxmarsc** [comment]
Hello davmon,

No worries, things takes time. Thanks for the answer !

- I don't think I used either OpenCL or Ref, but [ArmCL](https://github.com/ARM-software/ComputeLibrary). 
- Yes this is cross compilation on x86_64 host system, here is the [exact toolchain I used](https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz?rev=8d05006a68d24d929d602804ec9abfb4&hash=E8A66D3B9FF0EFC60A5C041AC3C5EE476349817B)
- I'm not using the build tool, but cmake directly as I needed to integrate armnn inside an existing cmake project (using CMake's ExternalProject feature). The only cmake flag I didn't mentioned in the issue was the `CMAKE_TOOLCHAIN_FILE` which I can provide if you want.

**Comment by davmon01** [comment]
Yes, please send it on if you don't mind. I added a patch making them inline, which is linked in the comment above. But it would still be good to replicate it so we can close off any gaps in our testing. :)

**Comment by maxmarsc** [comment]
Ok, so assuming you downloaded and extracted the [toolchain](https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz) under `/tmp/aarch64-none-linux-gnu-11.3.rel1`

Then the toolchain file would be :
__Toolchain.cmake__
```cmake
# targets
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(triple aarch64-linux-gnu)

# misc settings
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
set(GNU_ROOT "/tmp/aarch64-none-linux-gnu-11.3.rel1")
set(CMAKE_SYSROOT "${GNU_ROOT}/aarch64-none-linux-gnu/libc")

# find paths
set(CMAKE_FIND_ROOT_PATH "${GNU_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

# compiler settings
set(CMAKE_C_COMPILER "${GNU_ROOT}/bin/aarch64-none-linux-gnu-gcc" CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER "${GNU_ROOT}/bin/aarch64-none-linux-gnu-g++" CACHE INTERNAL "")

set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER_TARGET ${triple})

set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN "${GNU_ROOT}/lib/gcc")
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN "${GNU_ROOT}/lib/gcc")

# CPU tuning : the RPI 0 2W uses a Cortex a53
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mtune=cortex-a53" CACHE STRING "")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mtune=cortex-a53" CACHE STRING "")

# Qemu emulation setup
set(CMAKE_CROSSCOMPILING_EMULATOR "qemu-aarch64-static;-L;${CMAKE_SYSROOT}" CACHE FILEPATH "Path to the emulator for the target system.")

# Include settings
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES
  ${GNU_ROOT}/aarch64-none-linux-gnu/include/c++/11.3.1
  ${GNU_ROOT}/aarch64-none-linux-gnu/libc/usr/include
  ${GNU_ROOT}/include
  ${GNU_ROOT}/aarch64-none-linux-gnu/include/c++/11.3.1/aarch64-none-linux-gnu
  ${GNU_ROOT}/lib/gcc/aarch64-none-linux-gnu/11.3.1/include
)

set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES
  ${GNU_ROOT}/aarch64-none-linux-gnu/libc/usr/include
)
```

Then, to actually reproduce the issue I found out that ArmCL is not even needed, the simplest cmake configuration I found to reproduce was :
```bash
git clone git@github.com:ARM-software/armnn.git && cd armnn
git checkout v23.05
cmake -B build -DCMAKE_TOOLCHAIN_FILE=Toolchain.cmake  -DBUILD_SHARED_LIBS=OFF .
cmake --build build -j"$(ncpus)" --config Release
```

(you can simply replace `$(ncpus)` with the number of threads you want to use)

Hope this helps !

**Comment by davmon01** [comment]
Closing this off for now as a patch to fix the issue has been merged. If the issue reoccurs feel free to reopen the ticket. :)
