### ISSUE TITLE
Unable to Cross Compile ArmNN with the protobuf version 3.5.2 as it seems to be apparently missing

### ISSUE THREAD

**Issue by sarthak-chakraborty** [ARM-software/armnn#470]
I am trying to cross-compile the ArmNN library in my machine(Ubuntu 18.04, Intel x86_64 CPU architecture) and am following the steps as mentioned in [https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/BuildGuideCrossCompilation.md](https://github.com/ARM-software/armnn/blob/branches/armnn_20_08/BuildGuideCrossCompilation.md).

However, when I try to download protobuf version `3.5.2` and install, `protoc --version` return 3.5.1. I have even tried to download the specific tag [https://github.com/protocolbuffers/protobuf/releases/tag/v3.5.2](https://github.com/protocolbuffers/protobuf/releases/tag/v3.5.2) but to no avail. It still shows 3.5.1. I have ensured that there is no other libprotobuf in my machine except in the particular prefix as mentioned  in the Cross Compilation manual. 

Following a protobuf version 3.5.1, when I try to build ArmNN library, `make -j$(nproc)` fails because of the following error, where it demands a newer version of protoc.
```
In file included from /home/sarthak/onnx/onnx/onnx.pb.cc:4:0:
/home/sarthak/onnx/onnx/onnx.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~

/home/sarthak/onnx/onnx/onnx.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~

/home/sarthak/onnx/onnx/onnx.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
```

On the other hand, I have also tried as a sanity check to install protobuf version 3.6.0rc1 ([https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.0rc1](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.0rc1), returns 3.6.0 on `protoc --version`) and faced the following error while building ArmNN:
```
In file included from /home/sarthak/onnx/onnx/onnx.pb.cc:4:0:
/home/sarthak/onnx/onnx/onnx.pb.h:17:2: error: #error This file was generated by an newer version of protoc which is
 #error This file was generated by an newer version of protoc which is
  ^~~~~

/home/sarthak/onnx/onnx/onnx.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~

/home/sarthak/onnx/onnx/onnx.pb.h:19:2: error: #error regenerate this file with a older version of protoc.
 #error regenerate this file with a older version of protoc.
```

How to solve this issue? Does protobuf version 3.5.2 not exist?

Is there any downgraded version of ArmNN that can work with protobuf version 3.5.1 and if there is, what are its corresponding dependencies?

**Comment by MikeJKelly** [comment]
Hi @sarthak-chakraborty 

Is it possible that you have another version of protobuf installed somewhere on your build machine? What does `which protoc` return? 

Internally we have begun to use v3.12.0 of protobuf could you try with that one?

Best regards,
Mike
