### ISSUE TITLE
Build fail with catching polymorphic type by value error

### ISSUE THREAD

**Issue by ggardet** [ARM-software/armnn#123]
Build with GCC 8.2.1.
The full error message is:
```
[  147s] /home/abuild/rpmbuild/BUILD/armnn-18.11/src/armnn/LayerSupport.cpp:60:39: error: catching polymorphic type 'class armnn::InvalidArgumentException' by value [-Werror=catch-value=]
[  147s]      } catch (InvalidArgumentException e) { \
[  147s]                                        ^
```

**Comment by Surmeh** [comment]
Closing this ticket as I believe your issue has been resolved. Please re-open if I'm mistaken.
