### ISSUE TITLE
Slow execution speed on GpuAcc mode

### ISSUE THREAD

**Issue by Rahn80643** [ARM-software/armnn#534]
Hi,
I'm applying our segmentation model through ARM NN TfLite Delegate parser, and I discover the following result:
1. When the weight of the model is quantized as INT8 and it's invoked with GpuAcc backend, the invoke time is 9615ms
2. When the weight of the model is Float32 and it's invoked with GpuAcc backend, the invoke time is 760ms
The data type of both input and output are correctly set in ARM NN Tflite Delegate parser.

Does this mean the GPU I've used doesn't support INT8, so the parser is forced to convert the weight values from INT8 to Float32, and execute inference?

**Comment by MatthewARM** [comment]
@morgolock could this be a case where int8 isn't optimised enough? I'm surprised it would be slower than float32 though.

@Rahn80643 first thing to double check is that the GPU backend is correctly compiled and being loaded. The easiest way to check this is to turn on Arm NN logging, and maybe also event-based profiling. @matthewsloyanARM  do you know how to do that from the TfLite delegate?

**Comment by morgolock** [comment]
Hi @MatthewARM  and @Rahn80643 

We have found that the performance for int8 models is not as good as we would like and we are working to fix these problems. 

@Rahn80643 it would help if you could share the models you are using so that we can investigate this further. Would you also please share the commands you use to execute the models?

**Comment by Rahn80643** [comment]
Hi @morgolock, thanks for the quick reply

The attachment contains the tflite model I've used. And I have modified the program`armnn/tests/ExecuteNetwork/ExecuteNetwork.cpp` to load and infer my models.
[models.tar.gz](https://github.com/ARM-software/armnn/files/6342044/models.tar.gz)

And the following parameters I've used in my program:
- Input tensor name: `input_tensor`
- Output tensor name: `final_output`
- Input tensor dimension: `1,360,360,3`
- Input type: `float` for float model, `qasymm8` for quantized int8 model
- Output type: `int` for float model, `int` for quantized int8 model

Thank you,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

Thanks for sharing this.

What GPU did you run the models?

**Comment by matthewsloyanARM** [comment]
Hi @Rahn80643, 

Thanks for supplying the information and the model. Regarding the question from @MatthewARM logging can be turned on in the Arm NN TFLite Delegate by passing a log severity option to the DelegateOptions constructor. Below is an example of this.

`armnnDelegate::DelegateOptions delegateOptions(armnn::Compute::GpuAcc, backendOptions, armnn::LogSeverity::Debug);`

To enable event-based profiling the `-e` or `--event-based-profiling` flag can be added when running the ExecuteNetwork executable which can be found in your ArmNN build directory (armnn/tests). This will only work when running on the TfLiteParser  executor which is the default option for the `-T` or `--tflite-executor` flag, but it should be okay for this purpose. Thank you!

Kind regards,

Matthew

**Comment by MatthewARM** [comment]
@matthewsloyanARM does that mean there's no way to get event based profiling when using the TfLite delegate? We should fix that.

**Comment by Rahn80643** [comment]
@morgolock,
I used  Mali-G31 GPU to run the models, and I also install the package by `apt install mali-fbdev` to allow the gpu execute the models.

@matthewsloyanARM,
Thank you for giving the information, I will add this snippet into my code and check the information.

Thanks,
Rahn

**Comment by matthewsloyanARM** [comment]
@MatthewARM Yes there is currently no way through ExecuteNetwork, but I have added it to our backlog to add this support.

Kind regards,

Matthew

**Comment by Rahn80643** [comment]
Hi, 

The following is additional expriment:
I also applied the same INT8 model with ARM NN TfLite parser. 
The execution speed of the INT8 model on GpuAcc mode was also around  8900ms, which is slower than Float model on GpuAcc mode.

I will try to apply ` log severity option` to our program and check the result.

Rahn

**Comment by MatthewARM** [comment]
@Rahn80643 I've been thinking about possible reasons for this symptom, and it seems quite likely to me that major parts of the model are falling back from GpuAcc to CpuRef. 

The Arm NN logs and profiling output would confirm or eliminate this possibility.

Are you certain that OpenCL (needed for GPU acceleration) is working OK? If you can get an output from `clinfo` that would be very useful to check.

The bit that sometimes gets missed when setting up OpenCL for Mali on a board, is setting up the "vendor ICD" file so that OpenCL can select Mali as the provider.

One way of doing that is described in this forum post:
https://forum.odroid.com/viewtopic.php?t=30141

Hope that helps,
Matthew

**Comment by matthewsloyanARM** [comment]
To follow up on @MatthewARM comment above, the profiling data would be very useful to have a look at to confirm this along with the logging you will add. Would you be able to run your model through ExecuteNetwork with the --event-based-profiling flag if possible? An example of a command to do this based on the information you submitted can be found below. The the ExecuteNetwork executable can be found in your ArmNN build directory (armnn/tests) if tests have been enabled when building (-DBUILD_TESTS=1). Thank you!

`./ExecuteNetwork --compute GpuAcc --model-format tflite-binary --model-path <your_model_path> --input-tensor-shape 1,360,360,3  --input-name input_tensor --output-name final_output --input-type qasymm8 --output-type int --iterations 10 --event-based-profiling`

Kind regards, 

Matthew

**Comment by Rahn80643** [comment]
@matthewsloyanARM,
Hi, I've add `--event-based-profiling` in `./ExecuteNetwork` with `TfLiteParser`. And the attachment contains the profiled results as text files.

The following are execution speed of my models:
- Float32 TFLite model:
  - CpuRef: 60656.1 ms
  - CpuAcc: 716.75 ms
  - GpuAcc: 924.87 ms

- Int8 TFLite model:
  - CpuRef: 61813.61 ms
  - CpuAcc: 563.06 ms
  - GpuAcc: 8398.51 ms

Also, the result of `clinfo` is:
![clinfo](https://user-images.githubusercontent.com/8951991/115832768-dd740900-a445-11eb-9737-93d991aa6613.png)
[20210423_ARMNN_prof.tar.gz](https://github.com/ARM-software/armnn/files/6363410/20210423_ARMNN_prof.tar.gz)

Best regards,
Rahn

**Comment by MatthewARM** [comment]
Thanks @Rahn80643 all of that information is incredibly useful.

**Comment by Rahn80643** [comment]
Hi,

Will the issue above be solved in the next ARM NN release?

Best regards,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

We have identified where the problem is and we're working on a fix.

It won't be fixed until 21.08 but we'll provide a patch backward compatible which will work in 21.02 and 21.05.

Thank you for reporting this.

**Comment by morgolock** [comment]
Hi @Rahn80643 

This patch solves the performance problem for quantized models on G31

https://review.mlplatform.org/c/ml/ComputeLibrary/+/5858

Hope this helps.

**Comment by Rahn80643** [comment]
HI, @morgolock 
Thank you for informing the patch; when I compiled armnn 21.05 with this patch, I met the following error message:
'''
rmnn_2105/src/backends/cl/workloads/ClAbsWorkload.hpp:11:10: fatal error: arm_compute/runtime/CL/functions/CLElementWiseUnaryLayer.h: No such file or directory
 #include <arm_compute/runtime/CL/functions/CLElementWiseUnaryLayer.h>
'''
But I I can find CLElementWiseUnaryLayer.h in compute library of this patch. For comparison, armnn 21.05 could be compiled successfully with compute library 21.05 branch. Should I modify include path or makefile settings to compile armnn with compute library 21.05 patch?

(left: CLElementWiseUnaryLayer.h exists in compute library; right: error messge while compiling armnn)
![failed](https://user-images.githubusercontent.com/8951991/124352342-4e981f80-dc32-11eb-979b-bd35cf7c10e9.png)

**Comment by morgolock** [comment]
Hi @Rahn80643 

Please try with this other patch which applies cleanly to v21.05

https://review.mlplatform.org/c/ml/ComputeLibrary/+/5907

```
pabtel01@e124551:~/work/acl/ComputeLibrary$ git checkout v21.05
HEAD is now at 3bf76b1ade Fix heuristic in Int8 CLDirectConvolutionKernel
pabtel01@e124551:~/work/acl/ComputeLibrary$ git fetch https://review.mlplatform.org/ml/ComputeLibrary refs/changes/07/5907/2 && git cherry-pick FETCH_HEAD
remote: Counting objects: 3485, done
remote: Finding sources: 100% (16/16)
remote: Total 16 (delta 14), reused 15 (delta 14)
Unpacking objects: 100% (16/16), done.
From https://review.mlplatform.org/ml/ComputeLibrary
 * branch                  refs/changes/07/5907/2 -> FETCH_HEAD
[detached HEAD 65a575ce01] 21.05 development branch for int8 optimizations
 Author: Giorgio Arena <giorgio.arena@arm.com>
 Date: Mon Jul 5 13:38:58 2021 +0100
 8 files changed, 935 insertions(+), 471 deletions(-)
```

**Comment by Rahn80643** [comment]
Hi,
Thank you for providing the patch, I could successfully build armnn 21.05 with the Compute Library patch. And the execution 
speed of my uint8 model also increases on Mali G31 GPU.

However, when I applied the float model on Mali GPU, I met the following error: `Error: An error occurred when preparing the network workloads:  CL error: clCreateKernel. Error code: -45 at function MakeWorkload [/home/odroid/ARMNN_2105/armnn_2105/src/backends/cl/ClWorkloadFactory.cpp:110]`
The full error message as in the attachment.
[float_gpu_error.txt](https://github.com/ARM-software/armnn/files/6813756/float_gpu_error.txt)

Best regards,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

Could you please share with us the FP32 model which generates these issues?

**Comment by Rahn80643** [comment]
Hi,
the attachment contains the FP32 model:
input name: input_tensor
input dimension: 360x 360x 3
output name: final_output
output dimension: 180x 180

[float32_model.lite.tar.gz](https://github.com/ARM-software/armnn/files/6814742/float32_model.lite.tar.gz)

Best regards,
Rahn

**Comment by Rahn80643** [comment]
Hi, 
we also applied ExecuteNetwork to profile the execution speed of uint8 model on ARM NN with updated Compute Library. Compared to float model with privous Compute Library release, we found that the execution speed of softmax layer in uint8 model is slower than softmax layer in float model. The softmax layer takes 7.35% of the entire execution time in uint8 model; on the other hand, the softmax layer takes around 3.33% of the entire execution time in float model.
[profile_result.zip](https://github.com/ARM-software/armnn/files/6846807/profile_result.zip)

Is it possible to improve the execution speed of softmax layers?

Best Regards,
Rahn

**Comment by morgolock** [comment]
Hi @Rahn80643 

> we also applied ExecuteNetwork to profile the execution speed of uint8 model on ARM NN with updated Compute Library. Compared to float model with privous Compute Library release, we found that the execution speed of softmax layer in uint8 model is slower than softmax layer in float model. The softmax layer takes 7.35% of the entire execution time in uint8 model; on the other hand, the softmax layer takes around 3.33% of the entire execution time in float model.

Could you please clarify:

1. Which is the version of the updated library?
2. Which is the version of the previous library?
3. Which models are you referring to?


On G31 quantized models are expected to me slightly slower than fp32 due to the absence of dot product support.

**Comment by Rahn80643** [comment]
Hi,

1. The models we tested are the converted tflite model with FP32 and uint8 precision, these models are mentioned in the discussion above.

2. The version of previous library is ARM NN 21.02 with Compute Library 21.02, the FP32 model was tested with this version of ARM NN.

3. The version of updated library is ARM NN 21.05 with Compute Library updated patch (https://review.mlplatform.org/c/ml/ComputeLibrary/+/5907), the uint8 model was tested with this version of ARM NN.

**Comment by morgolock** [comment]
> Hi,
> Thank you for providing the patch, I could successfully build armnn 21.05 with the Compute Library patch. And the execution
> speed of my uint8 model also increases on Mali G31 GPU.
> 
> However, when I applied the float model on Mali GPU, I met the following error: `Error: An error occurred when preparing the network workloads: CL error: clCreateKernel. Error code: -45 at function MakeWorkload [/home/odroid/ARMNN_2105/armnn_2105/src/backends/cl/ClWorkloadFactory.cpp:110]`
> The full error message as in the attachment.
> [float_gpu_error.txt](https://github.com/ARM-software/armnn/files/6813756/float_gpu_error.txt)
> 
> Best regards,
> Rahn

Hi @Rahn80643 

I've just updated the patch to fix this problem.

Please could you try with the latest patchset (5).
https://github.com/ARM-software/armnn/issues/534

Hope this helps.

**Comment by morgolock** [comment]
Hi @Rahn80643 

> Hi,
> we also applied ExecuteNetwork to profile the execution speed of uint8 model on ARM NN with updated Compute Library. Compared to float model with privous Compute Library release, we found that the execution speed of softmax layer in uint8 model is slower than softmax layer in float model. The softmax layer takes 7.35% of the entire execution time in uint8 model; on the other hand, the softmax layer takes around 3.33% of the entire execution time in float model.
> [profile_result.zip](https://github.com/ARM-software/armnn/files/6846807/profile_result.zip)
> 
> Is it possible to improve the execution speed of softmax layers?
> 
> Best Regards,
> Rahn

Are you referring to BiSeNetv2_float.lite and BiSeNetv2_uint8.lite ?

```
root@odroid:~/pablo# python3 vison/vison.py -j BiSeNetv2_float.lite.proof | tail -n 30

Inference time:  735315.667 us
Total kernel time  640304.6419 us

Total time per kernel				Percentage of total time		Kernel name
	 21.6780              us 		% 0.00003386 			  gemm_mm_reshaped_only_rhs_t 
	 24.2550              us 		% 0.00003788 			  reduction_operation_y 
	 54.9540              us 		% 0.00008582 			  reduction_operation_z 
	 517.4760             us 		% 0.00080817 			  concatenate_width_x2 
	 610.2180             us 		% 0.00095301 			  fill_image_borders_constant 
	 805.2270             us 		% 0.00125757 			  pixelwise_mul_float 
	 893.3590             us 		% 0.00139521 			  activation_layer 
	 938.7490             us 		% 0.00146610 			  depthwise_convolution_3x3_nhwc 
	 1090.4610            us 		% 0.00170303 			  gemm_reshape_lhs_matrix_nt 
	 1248.5670            us 		% 0.00194996 			  gemm_mm_reshaped_lhs_nt_rhs_t 
	 1276.6560            us 		% 0.00199383 			  pooling_layer_MxN_nhwc 
	 1481.6300            us 		% 0.00231395 			  elementwise_operation_ADD 
	 2271.3090            us 		% 0.00354723 			  depthwise_convolution_3x3_stridex2_stridey2_f32 
	 2966.6480            us 		% 0.00463318 			  reshape_layer 
	 4089.4700            us 		% 0.00638676 			  depthwise_convolution_3x3_stridex1_stridey1_f32 
	 4176.9500            us 		% 0.00652338 			  depthwise_convolution_3x3_nhwc_stride1 
	 11842.5860           us 		% 0.01849524 			  softmax_layer_norm 
	 15025.9490           us 		% 0.02346688 			  im2col3x3_nhwc 
	 16433.1250           us 		% 0.02566454 			  softmax_layer_max_shift_exp_sum_serial 
	 17526.0700           us 		% 0.02737146 			  winograd_output_transform_4x4_3x3_nhwc 
	 26331.9740           us 		% 0.04112413 			  arg_min_max_x 
	 29888.0950           us 		% 0.04667793 			  permute 
	 44669.7030           us 		% 0.06976320 			  winograd_input_transform_4x4_3x3_stepz1_nhwc 
	 78658.5800           us 		% 0.12284556 			  scale_bilinear_nhwc 
	 377460.9530          us 		% 0.58950213 			  gemm_mm_floating_point_f32_bifrost 
```

```
root@odroid:~/pablo# python3 vison/vison.py -j BiSeNetv2_uint8.lite.proof | tail -n 26


Inference time:  1671566.584 us
Total kernel time  1609005.1670 us

Total time per kernel				Percentage of total time		Kernel name
	 14.4390              us 		% 0.00000897 			  reduction_operation_y 
	 16.3560              us 		% 0.00001017 			  reduction_operation_z 
	 231.2780             us 		% 0.00014374 			  activation_layer_quant 
	 450.7610             us 		% 0.00028015 			  concatenate_width_x2 
	 451.6880             us 		% 0.00028073 			  pixelwise_mul_quantized 
	 606.3080             us 		% 0.00037682 			  fill_image_borders_constant 
	 645.6590             us 		% 0.00040128 			  pooling_layer_MxN_quantized_nhwc 
	 750.5530             us 		% 0.00046647 			  elementwise_operation_ADD_quantized 
	 905.2430             us 		% 0.00056261 			  activation_layer_quant_f32 
	 2971.9250            us 		% 0.00184706 			  reshape_layer 
	 5762.5760            us 		% 0.00358145 			  dwc_MxN_native_quantized8_nhwc 
	 13739.5280           us 		% 0.00853914 			  dwc_3x3_native_quantized8_nchw 
	 23322.8410           us 		% 0.01449519 			  gemmlowp_matrix_a_reduction 
	 24977.7740           us 		% 0.01552374 			  arg_min_max_x 
	 32896.1260           us 		% 0.02044501 			  permute 
	 61229.6540           us 		% 0.03805436 			  im2col3x3_nhwc 
	 87643.7010           us 		% 0.05447074 			  scale_bilinear_quantized_nhwc 
	 163478.6300          us 		% 0.10160230 			  softmax_layer_max_shift_exp_sum_quantized_serial 
	 201701.4210          us 		% 0.12535785 			  softmax_layer_norm_quantized 
	 987208.7060          us 		% 0.61355223 			  gemmlowp_mm_reshaped_only_rhs_t_fused_output_stage_fixedpoint 
```

**Comment by Rahn80643** [comment]
> Hi @Rahn80643
> 
> > Hi,
> > we also applied ExecuteNetwork to profile the execution speed of uint8 model on ARM NN with updated Compute Library. Compared to float model with privous Compute Library release, we found that the execution speed of softmax layer in uint8 model is slower than softmax layer in float model. The softmax layer takes 7.35% of the entire execution time in uint8 model; on the other hand, the softmax layer takes around 3.33% of the entire execution time in float model.
> > [profile_result.zip](https://github.com/ARM-software/armnn/files/6846807/profile_result.zip)
> > Is it possible to improve the execution speed of softmax layers?
> > Best Regards,
> > Rahn
> 
> Are you referring to BiSeNetv2_float.lite and BiSeNetv2_uint8.lite ?
> 
> ```
> root@odroid:~/pablo# python3 vison/vison.py -j BiSeNetv2_float.lite.proof | tail -n 30
> 
> Inference time:  735315.667 us
> Total kernel time  640304.6419 us
> 
> Total time per kernel				Percentage of total time		Kernel name
> 	 21.6780              us 		% 0.00003386 			  gemm_mm_reshaped_only_rhs_t 
> 	 24.2550              us 		% 0.00003788 			  reduction_operation_y 
> 	 54.9540              us 		% 0.00008582 			  reduction_operation_z 
> 	 517.4760             us 		% 0.00080817 			  concatenate_width_x2 
> 	 610.2180             us 		% 0.00095301 			  fill_image_borders_constant 
> 	 805.2270             us 		% 0.00125757 			  pixelwise_mul_float 
> 	 893.3590             us 		% 0.00139521 			  activation_layer 
> 	 938.7490             us 		% 0.00146610 			  depthwise_convolution_3x3_nhwc 
> 	 1090.4610            us 		% 0.00170303 			  gemm_reshape_lhs_matrix_nt 
> 	 1248.5670            us 		% 0.00194996 			  gemm_mm_reshaped_lhs_nt_rhs_t 
> 	 1276.6560            us 		% 0.00199383 			  pooling_layer_MxN_nhwc 
> 	 1481.6300            us 		% 0.00231395 			  elementwise_operation_ADD 
> 	 2271.3090            us 		% 0.00354723 			  depthwise_convolution_3x3_stridex2_stridey2_f32 
> 	 2966.6480            us 		% 0.00463318 			  reshape_layer 
> 	 4089.4700            us 		% 0.00638676 			  depthwise_convolution_3x3_stridex1_stridey1_f32 
> 	 4176.9500            us 		% 0.00652338 			  depthwise_convolution_3x3_nhwc_stride1 
> 	 11842.5860           us 		% 0.01849524 			  softmax_layer_norm 
> 	 15025.9490           us 		% 0.02346688 			  im2col3x3_nhwc 
> 	 16433.1250           us 		% 0.02566454 			  softmax_layer_max_shift_exp_sum_serial 
> 	 17526.0700           us 		% 0.02737146 			  winograd_output_transform_4x4_3x3_nhwc 
> 	 26331.9740           us 		% 0.04112413 			  arg_min_max_x 
> 	 29888.0950           us 		% 0.04667793 			  permute 
> 	 44669.7030           us 		% 0.06976320 			  winograd_input_transform_4x4_3x3_stepz1_nhwc 
> 	 78658.5800           us 		% 0.12284556 			  scale_bilinear_nhwc 
> 	 377460.9530          us 		% 0.58950213 			  gemm_mm_floating_point_f32_bifrost 
> ```
> 
> ```
> root@odroid:~/pablo# python3 vison/vison.py -j BiSeNetv2_uint8.lite.proof | tail -n 26
> 
> 
> Inference time:  1671566.584 us
> Total kernel time  1609005.1670 us
> 
> Total time per kernel				Percentage of total time		Kernel name
> 	 14.4390              us 		% 0.00000897 			  reduction_operation_y 
> 	 16.3560              us 		% 0.00001017 			  reduction_operation_z 
> 	 231.2780             us 		% 0.00014374 			  activation_layer_quant 
> 	 450.7610             us 		% 0.00028015 			  concatenate_width_x2 
> 	 451.6880             us 		% 0.00028073 			  pixelwise_mul_quantized 
> 	 606.3080             us 		% 0.00037682 			  fill_image_borders_constant 
> 	 645.6590             us 		% 0.00040128 			  pooling_layer_MxN_quantized_nhwc 
> 	 750.5530             us 		% 0.00046647 			  elementwise_operation_ADD_quantized 
> 	 905.2430             us 		% 0.00056261 			  activation_layer_quant_f32 
> 	 2971.9250            us 		% 0.00184706 			  reshape_layer 
> 	 5762.5760            us 		% 0.00358145 			  dwc_MxN_native_quantized8_nhwc 
> 	 13739.5280           us 		% 0.00853914 			  dwc_3x3_native_quantized8_nchw 
> 	 23322.8410           us 		% 0.01449519 			  gemmlowp_matrix_a_reduction 
> 	 24977.7740           us 		% 0.01552374 			  arg_min_max_x 
> 	 32896.1260           us 		% 0.02044501 			  permute 
> 	 61229.6540           us 		% 0.03805436 			  im2col3x3_nhwc 
> 	 87643.7010           us 		% 0.05447074 			  scale_bilinear_quantized_nhwc 
> 	 163478.6300          us 		% 0.10160230 			  softmax_layer_max_shift_exp_sum_quantized_serial 
> 	 201701.4210          us 		% 0.12535785 			  softmax_layer_norm_quantized 
> 	 987208.7060          us 		% 0.61355223 			  gemmlowp_mm_reshaped_only_rhs_t_fused_output_stage_fixedpoint 
> ```

Yes, BiSeNetv2_float.lite and BiSeNetv2_uint8.lite are referred.
