### ISSUE TITLE
UnitTests errors

### ISSUE THREAD

**Issue by georgeokelly** [ARM-software/armnn#155]
Hi I build and run the UnitTests but there are 4 failures detected and below is the log. I follow the instructions except that I set `opencl=0` when building Compute Library and `- DARMCOMPUTECL=0` when building ArmNN. Besides, I build on Ubuntu 16.04 and my device is with Android 8.1.0

```
Running 1108 test cases...
/home/ndk/armnn-devenv/armnn/src/backends/reference/test/RefCreateWorkloadTests.cpp(21): error: in "CreateWorkloadRef/CreateConvolution2dFloatNchwWorkload": check (inputHandle->GetTensorInfo() == inputInfo) has failed
/home/ndk/armnn-devenv/armnn/src/backends/reference/test/RefCreateWorkloadTests.cpp(22): error: in "CreateWorkloadRef/CreateConvolution2dFloatNchwWorkload": check (outputHandle->GetTensorInfo() == outputInfo) has failed
/home/ndk/armnn-devenv/armnn/src/backends/reference/test/RefCreateWorkloadTests.cpp(21): error: in "CreateWorkloadRef/CreateConvolution2dFloatNhwcWorkload": check (inputHandle->GetTensorInfo() == inputInfo) has failed
/home/ndk/armnn-devenv/armnn/src/backends/reference/test/RefCreateWorkloadTests.cpp(22): error: in "CreateWorkloadRef/CreateConvolution2dFloatNhwcWorkload": check (outputHandle->GetTensorInfo() == outputInfo) has failed

*** 4 failures are detected in the test module "UnitTests"

```
Thanks.

**Comment by georgeokelly** [comment]
It has been solved with the NDK r17c on Ubuntu 18.04 #81
